const packs = [
    {
        title: "Make Some Noise",
        coverImage: require('../assets/packIcon0.png'),
        prompts: [
            "Dog",
            "Cat",
            "Car Engine Starting",
            "Rain Falling",
            "Thunder Rumbling",
            "Doorbell Ringing",
            "Bird Chirping",
            "Water Dripping",
            "Brushing Teeth",
            "Typing on a Keyboard",
            "Ringing a Bell",
            "Playing Guitar",
            "Playing Piano",
            "Playing Drums",
            "Clapping",
            "Zipping up a Jacket",
            "Cracking Knuckles",
            "Ripping Paper",
            "Pouring Water",
            "Eating Chips",
            "Opening a Soda Can",
            "Shaking a Cocktail",
            "Chopping Vegetables",
            "Sizzling",
            "Cracking an Egg",
            "Blender",
            "Boiling water",
            "Whisking",
            "Grating Carrot",
            "Brewing Coffee",
            "Pouring Cereal",
            "Popping Popcorn",
            "Buttering Toast",
            "Eating Soup",
            "Sipping Tea",
            "Inflating Balloon",
            "Popping Balloon",
            "Crunching Leaves",
            "Sweeping the Floor",
            "Vacuuming",
            "Mowing the Lawn",
            "Raking Leaves",
            "Shoveling Snow",
            "Digging a Hole",
            "Hammering Nails",
            "Sawing Wood",
            "Drilling",
            "Sanding Wood",
            "Paint Roller",
            "Spray Paint",
        ]
    },
    {
        title: "Classic Charades",
        coverImage: require('../assets/packIcon1.png'),
        prompts: [
            "Dog",
            "Cat",
            
        ]
    }
  
];

export default packs;